services:
  airflow:
    image: apache/airflow:2.10.5
    container_name: airflow_supply_chain
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./app:/opt/airflow/app
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
    command: >
      bash -c "
      airflow db init &&
      airflow users create
      --username admin
      --password admin
      --firstname Kevin
      --lastname User
      --role Admin
      --email kevin@example.com &&
      airflow standalone
      "